### ISSUE TITLE
テストの記述

### ISSUE THREAD

**Issue by neila** [unchain-tech/Solana-Online-Store#3]
- [x] 提出物が学習コンテンツ通りに作成されているかの動作確認ができる、テストスクリプトを追加する
- [x] https://github.com/shiftbase-inc/UNCHAIN-test-submissions から実行できるようにする

**Comment by yk-saito** [comment]
CodeBuild上で動作確認完了しました。
- [build logs](https://ap-northeast-1.console.aws.amazon.com/codesuite/codebuild/733910873054/projects/stg-codetest/build/stg-codetest%3A8b201243-897d-4e3a-9729-c260d20988f2/env_var?region=ap-northeast-1)
